#!/bin/bash
set -e

echo "� Running post-deployment setup..."

# Original setup for credentials
echo "�💡 (Optional) To setup username and password for the web application, run './scripts/setup_credential.sh'."

# Setup APIM environment and run tests
echo "🔧 Setting up APIM environment and running tests..."

# Check if jq is available, install if needed
if ! command -v jq &> /dev/null; then
    echo "📦 Installing jq for JSON parsing..."
    if command -v apt-get &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y jq
    elif command -v yum &> /dev/null; then
        sudo yum install -y jq
    elif command -v brew &> /dev/null; then
        brew install jq
    else
        echo "⚠️ Please install jq manually to continue"
        exit 1
    fi
fi

# Get APIM outputs from azd
echo "📋 Getting deployment outputs..."
APIM_GATEWAY_URL=$(azd env get-values --output json | jq -r '.APIM_GATEWAY_URL // empty')
APIM_SUBSCRIPTION_ID=$(azd env get-values --output json | jq -r '.APIM_SUBSCRIPTION_ID // empty')
RESOURCE_GROUP=$(azd env get-values --output json | jq -r '.AZURE_RESOURCE_GROUP // empty')
APIM_SERVICE_NAME=$(azd env get-values --output json | jq -r '.APIM_SERVICE_NAME // empty')

if [ -z "$APIM_GATEWAY_URL" ] || [ -z "$APIM_SUBSCRIPTION_ID" ]; then
    echo "❌ APIM environment variables not found. Make sure deployment completed successfully."
    echo "📋 Available environment variables:"
    azd env get-values
    exit 1
fi

echo "✅ APIM Gateway URL: $APIM_GATEWAY_URL"
echo "✅ APIM Service Name: $APIM_SERVICE_NAME"

# Get subscription key
echo "🔑 Retrieving APIM subscription key..."
APIM_SUBSCRIPTION_KEY=$(az apim subscription list-secrets \
    --resource-group "$RESOURCE_GROUP" \
    --service-name "$APIM_SERVICE_NAME" \
    --subscription-id "default-subscription" \
    --query "primaryKey" -o tsv)

if [ -z "$APIM_SUBSCRIPTION_KEY" ]; then
    echo "❌ Failed to retrieve APIM subscription key"
    exit 1
fi

echo "✅ APIM Subscription Key: ${APIM_SUBSCRIPTION_KEY:0:8}..."

# Create frontend .env file
FRONTEND_ENV_FILE="src/frontend/.env"
echo "📝 Creating frontend environment file: $FRONTEND_ENV_FILE"

cat > "$FRONTEND_ENV_FILE" << EOF
# APIM Configuration - Generated by postdeploy script
VITE_APIM_SUBSCRIPTION_KEY=$APIM_SUBSCRIPTION_KEY
EOF

echo "✅ Frontend environment file created!"

# Install Python dependencies for testing if not already installed
if ! python3 -c "import requests" 2>/dev/null; then
    echo "📦 Installing Python testing dependencies..."
    pip3 install requests
fi

# Run E2E tests
echo "🧪 Running end-to-end tests..."
if python3 test_e2e.py --apim-url "$APIM_GATEWAY_URL" --subscription-key "$APIM_SUBSCRIPTION_KEY"; then
    echo "🎉 All tests passed! Your APIM architecture is working correctly."
    echo ""
    echo "🌐 Access your application at: $APIM_GATEWAY_URL"
    echo "🔑 Use subscription key: $APIM_SUBSCRIPTION_KEY"
    echo ""
    echo "📚 Next steps:"
    echo "   - Test the React frontend at: $APIM_GATEWAY_URL"
    echo "   - Monitor API usage in Azure Portal"
    echo "   - Configure additional APIM policies as needed"
else
    echo "⚠️ Some tests failed. Please check the logs above for details."
    echo "🔧 Troubleshooting tips:"
    echo "   - Check APIM service status in Azure Portal"
    echo "   - Verify Container App is running"
    echo "   - Check API backend health at: $APIM_GATEWAY_URL/api/health"
fi

echo ""
echo "✅ Post-deployment setup complete!"